# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class Configuration
    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    @array_serialization = 'indexed'

    # An enum for SDK environments
    class Environment
      #SANDBOX: https://sandbox.gonebusy.com/api/v1
      ENVIRONMENT = [PRODUCTION = 0, SANDBOX = 1]
    end

    # An enum for API servers
    class Server
      SERVER = [DEFAULT = 0]
    end

    # The environment in which the SDK is running
    @environment = Environment::PRODUCTION

    # Set Authorization to "Token <your API key>"
    @authorization = 'Token <your API key>'

    # All the environments the SDK can run in
    @environments = {
      Environment::PRODUCTION => {
        Server::DEFAULT => 'https://beta.gonebusy.com/api/v1',
      },
      Environment::SANDBOX => {
        Server::DEFAULT => 'https://sandbox.gonebusy.com/api/v1',
      },
    }

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] The server enum for which the base URI is required.
    # @return [String] The base URI.
    def self.get_base_uri(server = Server::DEFAULT)
      environments[environment][server]
    end

    # The attribute accessors for public properties
    class << self
      attr_accessor :array_serialization
      attr_accessor :environment
      attr_accessor :environments
      attr_accessor :authorization
    end
  end
end
