# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class CreateBookingBody < BaseModel
    # Desired date of booking.  Several formats are supported: "2014-10-31", "October 31, 2014"
    # @return [Date]
    attr_accessor :date

    # ID of Service being booked
    # @return [Integer]
    attr_accessor :service_id

    # Desired time of booking.  Several formats are supported: '9am', '09:00', '9:00', '0900'
    # @return [String]
    attr_accessor :time

    # Required only when :recurs_by is 'monthly' or 'yearly' to differentiate between exact date or 'day in month/year'.  See Recurring Booking examples.
    # @return [DateRecursByEnum]
    attr_accessor :date_recurs_by

    # List of comma-separated days of the week this Booking falls on.  Useful for recurring Bookings.  If provided, at least one must be specified.
    # @return [String]
    attr_accessor :days

    # Length of time, in minutes, for the desired booking - if Service allows requesting a variable amount of time
    # @return [Integer]
    attr_accessor :duration

    # Optional end date if a recurring booking - i.e, :recurs_by other than :once.  If recurring, leave blank for infinite booking.  Several formats are supported: '2014-10-31', 'October 31, 2014'.
    # @return [Date]
    attr_accessor :end_date

    # Optional frequency of recurrence as specified by :recurs_by.  E.g, :single, :every, :every_other, etc. If not provided, assumed to be :once
    # @return [FrequencyEnum]
    attr_accessor :frequency

    # Optional occurrence of frequency. E.g, :first, :2nd, :last, :2nd_to_last, etc.  If not provided, assumed to be :every
    # @return [OccurrenceEnum]
    attr_accessor :occurrence

    # One of the possible recurrence values.  If not provided, assumed to be :once to indicate a single Booking.
    # @return [RecursByEnum]
    attr_accessor :recurs_by

    # ID of a Resource to be booked.  If not provided, the first available Resource will be booked.
    # @return [Integer]
    attr_accessor :resource_id

    # Create a booking for this User Id.  You must be authorized to manage this User Id.
    # @return [Integer]
    attr_accessor :user_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["date"] = "date"
        @hash["service_id"] = "service_id"
        @hash["time"] = "time"
        @hash["date_recurs_by"] = "date_recurs_by"
        @hash["days"] = "days"
        @hash["duration"] = "duration"
        @hash["end_date"] = "end_date"
        @hash["frequency"] = "frequency"
        @hash["occurrence"] = "occurrence"
        @hash["recurs_by"] = "recurs_by"
        @hash["resource_id"] = "resource_id"
        @hash["user_id"] = "user_id"
      end
      @hash
    end

    def initialize(date = nil,
                   service_id = nil,
                   time = nil,
                   date_recurs_by = nil,
                   days = nil,
                   duration = nil,
                   end_date = nil,
                   frequency = nil,
                   occurrence = nil,
                   recurs_by = nil,
                   resource_id = nil,
                   user_id = nil)
      @date = date
      @service_id = service_id
      @time = time
      @date_recurs_by = date_recurs_by
      @days = days
      @duration = duration
      @end_date = end_date
      @frequency = frequency
      @occurrence = occurrence
      @recurs_by = recurs_by
      @resource_id = resource_id
      @user_id = user_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        date = hash['date']
        service_id = hash['service_id']
        time = hash['time']
        date_recurs_by = hash['date_recurs_by']
        days = hash['days']
        duration = hash['duration']
        end_date = hash['end_date']
        frequency = hash['frequency']
        occurrence = hash['occurrence']
        recurs_by = hash['recurs_by']
        resource_id = hash['resource_id']
        user_id = hash['user_id']

        # Create object from extracted values
        CreateBookingBody.new(date,
                              service_id,
                              time,
                              date_recurs_by,
                              days,
                              duration,
                              end_date,
                              frequency,
                              occurrence,
                              recurs_by,
                              resource_id,
                              user_id)
      end
    end
  end
end
