# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class CreatePricingModelBody < BaseModel
    # PricingModel Name
    # @return [String]
    attr_accessor :name

    # Type of PricingModel
    # @return [String]
    attr_accessor :type

    # Create a PricingModel for this User Id.  You must be authorized to manage this User Id.
    # @return [Integer]
    attr_accessor :user_id

    # Optional Notes Field
    # @return [String]
    attr_accessor :notes

    # Price
    # @return [Float]
    attr_accessor :price

    # 3 Letter ISO Currency Code
    # @return [String]
    attr_accessor :currency

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["name"] = "name"
        @_hash["type"] = "type"
        @_hash["user_id"] = "user_id"
        @_hash["notes"] = "notes"
        @_hash["price"] = "price"
        @_hash["currency"] = "currency"
      end
      @_hash
    end

    def initialize(name = nil,
                   type = nil,
                   user_id = nil,
                   notes = nil,
                   price = nil,
                   currency = nil)
      @name = name
      @type = type
      @user_id = user_id
      @notes = notes
      @price = price
      @currency = currency
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      name = hash['name']
      type = hash['type']
      user_id = hash['user_id']
      notes = hash['notes']
      price = hash['price']
      currency = hash['currency']

      # Create object from extracted values
      CreatePricingModelBody.new(name,
                                 type,
                                 user_id,
                                 notes,
                                 price,
                                 currency)
    end
  end
end
