# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class CreateResourceBody < BaseModel
    # Resource Name
    # @return [String]
    attr_accessor :name

    # Type of Resource
    # @return [String]
    attr_accessor :type

    # Create a Resource for this User Id.  You must be authorized to manage this User Id.
    # @return [Integer]
    attr_accessor :user_id

    # Optional Description
    # @return [String]
    attr_accessor :description

    # Optional Capacity
    # @return [Integer]
    attr_accessor :capacity

    # Optional Gender
    # @return [GenderEnum]
    attr_accessor :gender

    # When Resource is a Thing, the type Id
    # @return [Integer]
    attr_accessor :thing_type_id

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["name"] = "name"
        @_hash["type"] = "type"
        @_hash["user_id"] = "user_id"
        @_hash["description"] = "description"
        @_hash["capacity"] = "capacity"
        @_hash["gender"] = "gender"
        @_hash["thing_type_id"] = "thing_type_id"
      end
      @_hash
    end

    def initialize(name = nil,
                   type = nil,
                   user_id = nil,
                   description = nil,
                   capacity = nil,
                   gender = nil,
                   thing_type_id = nil)
      @name = name
      @type = type
      @user_id = user_id
      @description = description
      @capacity = capacity
      @gender = gender
      @thing_type_id = thing_type_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      name = hash['name']
      type = hash['type']
      user_id = hash['user_id']
      description = hash['description']
      capacity = hash['capacity']
      gender = hash['gender']
      thing_type_id = hash['thing_type_id']

      # Create object from extracted values
      CreateResourceBody.new(name,
                             type,
                             user_id,
                             description,
                             capacity,
                             gender,
                             thing_type_id)
    end
  end
end
