# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class DateRecursByEnum
    # TODO: Write general description for DAY_IN_MONTH
    # TODO: Write general description for DAY_IN_YEAR
    # TODO: Write general description for DATE_IN_MONTH
    # TODO: Write general description for DATE_IN_YEAR
    # TODO: Write general description for DAY_IN_QUARTER
    # TODO: Write general description for DATE_IN_QUARTER
    DATE_RECURS_BY_ENUM = [DAY_IN_MONTH = 'day_in_month', DAY_IN_YEAR = 'day_in_year', DATE_IN_MONTH = 'date_in_month', DATE_IN_YEAR = 'date_in_year', DAY_IN_QUARTER = 'day_in_quarter', DATE_IN_QUARTER = 'date_in_quarter']
  end
end