# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class DeleteResourceByIdResponse < BaseModel
    # TODO: Write general description for this method
    # @return [EntitiesResourceResponse]
    attr_accessor :resource

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["resource"] = "resource"
      end
      @_hash
    end

    def initialize(resource = nil)
      @resource = resource
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      resource = EntitiesResourceResponse.from_hash(hash['resource']) if hash['resource']

      # Create object from extracted values
      DeleteResourceByIdResponse.new(resource)
    end
  end
end
