# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class DeleteScheduleByIdResponse < BaseModel
    # TODO: Write general description for this method
    # @return [EntitiesScheduleResponse]
    attr_accessor :schedule

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["schedule"] = "schedule"
      end
      @_hash
    end

    def initialize(schedule = nil)
      @schedule = schedule
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      schedule = EntitiesScheduleResponse.from_hash(hash['schedule']) if hash['schedule']

      # Create object from extracted values
      DeleteScheduleByIdResponse.new(schedule)
    end
  end
end
