# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class EntitiesResourceAvailabilities < BaseModel
    # id of Resource
    # @return [Integer]
    attr_accessor :id

    # array of available date and time slots
    # @return [List of EntitiesSlots]
    attr_accessor :available_slots

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["id"] = "id"
        @_hash["available_slots"] = "available_slots"
      end
      @_hash
    end

    def initialize(id = nil,
                   available_slots = nil)
      @id = id
      @available_slots = available_slots
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      id = hash['id']
      # Parameter is an array, so we need to iterate through it
      available_slots = nil
      if hash['available_slots'] != nil
        available_slots = Array.new
        hash['available_slots'].each{|structure| available_slots << (EntitiesSlots.from_hash(structure) if structure)}
      end

      # Create object from extracted values
      EntitiesResourceAvailabilities.new(id,
                                         available_slots)
    end
  end
end
