# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class EntitiesAddressEntity < BaseModel
    # line 1 of Address
    # @return [String]
    attr_accessor :line_1

    # line 2 of Address
    # @return [String]
    attr_accessor :line_2

    # city of Address
    # @return [String]
    attr_accessor :city

    # state of Address
    # @return [String]
    attr_accessor :state

    # province of Address
    # @return [String]
    attr_accessor :province

    # postal code of Address
    # @return [String]
    attr_accessor :postal_code

    # country of Address
    # @return [String]
    attr_accessor :country

    # country code of Address
    # @return [String]
    attr_accessor :country_code

    # latitude of Address
    # @return [String]
    attr_accessor :latitude

    # longitude of Address
    # @return [String]
    attr_accessor :longitude

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["line_1"] = "line1"
        @_hash["line_2"] = "line2"
        @_hash["city"] = "city"
        @_hash["state"] = "state"
        @_hash["province"] = "province"
        @_hash["postal_code"] = "postal_code"
        @_hash["country"] = "country"
        @_hash["country_code"] = "country_code"
        @_hash["latitude"] = "latitude"
        @_hash["longitude"] = "longitude"
      end
      @_hash
    end

    def initialize(line_1 = nil,
                   line_2 = nil,
                   city = nil,
                   state = nil,
                   province = nil,
                   postal_code = nil,
                   country = nil,
                   country_code = nil,
                   latitude = nil,
                   longitude = nil)
      @line_1 = line_1
      @line_2 = line_2
      @city = city
      @state = state
      @province = province
      @postal_code = postal_code
      @country = country
      @country_code = country_code
      @latitude = latitude
      @longitude = longitude
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      line_1 = hash['line1']
      line_2 = hash['line2']
      city = hash['city']
      state = hash['state']
      province = hash['province']
      postal_code = hash['postal_code']
      country = hash['country']
      country_code = hash['country_code']
      latitude = hash['latitude']
      longitude = hash['longitude']

      # Create object from extracted values
      EntitiesAddressEntity.new(line_1,
                                line_2,
                                city,
                                state,
                                province,
                                postal_code,
                                country,
                                country_code,
                                latitude,
                                longitude)
    end
  end
end
