# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class EntitiesSlots < BaseModel
    # date of availability
    # @return [Date]
    attr_accessor :date

    # array of available time slots
    # @return [List of String]
    attr_accessor :slots

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["date"] = "date"
        @_hash["slots"] = "slots"
      end
      @_hash
    end

    def initialize(date = nil,
                   slots = nil)
      @date = date
      @slots = slots
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      date = hash['date']
      slots = hash['slots']

      # Create object from extracted values
      EntitiesSlots.new(date,
                        slots)
    end
  end
end
