# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class EntitiesCategoryResponse < BaseModel
    # id of Category
    # @return [Integer]
    attr_accessor :id

    # name of Category
    # @return [String]
    attr_accessor :name

    # abbreviated name for Category
    # @return [String]
    attr_accessor :short_name

    # extended name for Category
    # @return [String]
    attr_accessor :long_name

    # description of Category
    # @return [String]
    attr_accessor :description

    # id of parent Category, if any
    # @return [Integer]
    attr_accessor :parent_category_id

    # status of Category
    # @return [Boolean]
    attr_accessor :is_active

    # array of subcategory ids, if any
    # @return [List of Integer]
    attr_accessor :subcategories

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["id"] = "id"
        @_hash["name"] = "name"
        @_hash["short_name"] = "short_name"
        @_hash["long_name"] = "long_name"
        @_hash["description"] = "description"
        @_hash["parent_category_id"] = "parent_category_id"
        @_hash["is_active"] = "is_active"
        @_hash["subcategories"] = "subcategories"
      end
      @_hash
    end

    def initialize(id = nil,
                   name = nil,
                   short_name = nil,
                   long_name = nil,
                   description = nil,
                   parent_category_id = nil,
                   is_active = nil,
                   subcategories = nil)
      @id = id
      @name = name
      @short_name = short_name
      @long_name = long_name
      @description = description
      @parent_category_id = parent_category_id
      @is_active = is_active
      @subcategories = subcategories
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      id = hash['id']
      name = hash['name']
      short_name = hash['short_name']
      long_name = hash['long_name']
      description = hash['description']
      parent_category_id = hash['parent_category_id']
      is_active = hash['is_active']
      subcategories = hash['subcategories']

      # Create object from extracted values
      EntitiesCategoryResponse.new(id,
                                   name,
                                   short_name,
                                   long_name,
                                   description,
                                   parent_category_id,
                                   is_active,
                                   subcategories)
    end
  end
end
