# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class EntitiesBookingResponse < BaseModel
    # id of Booking
    # @return [Integer]
    attr_accessor :id

    # id of owner of Booking
    # @return [Integer]
    attr_accessor :owner_id

    # status of Booking
    # @return [String]
    attr_accessor :workflow_state

    # user requesting Booking may include a message
    # @return [String]
    attr_accessor :user_message

    # TimeWindow corresponding to Booking
    # @return [EntitiesTimeWindowResponse]
    attr_accessor :time_window

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["id"] = "id"
        @_hash["owner_id"] = "owner_id"
        @_hash["workflow_state"] = "workflow_state"
        @_hash["user_message"] = "user_message"
        @_hash["time_window"] = "time_window"
      end
      @_hash
    end

    def initialize(id = nil,
                   owner_id = nil,
                   workflow_state = nil,
                   user_message = nil,
                   time_window = nil)
      @id = id
      @owner_id = owner_id
      @workflow_state = workflow_state
      @user_message = user_message
      @time_window = time_window
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      id = hash['id']
      owner_id = hash['owner_id']
      workflow_state = hash['workflow_state']
      user_message = hash['user_message']
      time_window = EntitiesTimeWindowResponse.from_hash(hash['time_window']) if hash['time_window']

      # Create object from extracted values
      EntitiesBookingResponse.new(id,
                                  owner_id,
                                  workflow_state,
                                  user_message,
                                  time_window)
    end
  end
end
