# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class EntitiesServiceResponse < BaseModel
    # array of Category ids Service belongs to
    # @return [List of Integer]
    attr_accessor :categories

    # description of Service
    # @return [String]
    attr_accessor :description

    # length of Service in minutes
    # @return [Integer]
    attr_accessor :duration

    # id of Service
    # @return [Integer]
    attr_accessor :id

    # status of Service
    # @return [Boolean]
    attr_accessor :is_active

    # max length of Service in minutes
    # @return [Integer]
    attr_accessor :max_duration

    # name of Service
    # @return [String]
    attr_accessor :name

    # id of owner of Service
    # @return [Integer]
    attr_accessor :owner_id

    # id of Pricing Model
    # @return [Integer]
    attr_accessor :price_model_id

    # array of Resource ids offering Service
    # @return [List of Integer]
    attr_accessor :resources

    # array of Schedule ids, one for each Resource offering Service
    # @return [List of Integer]
    attr_accessor :schedules

    # abbreviated name for Service
    # @return [String]
    attr_accessor :short_name

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["categories"] = "categories"
        @hash["description"] = "description"
        @hash["duration"] = "duration"
        @hash["id"] = "id"
        @hash["is_active"] = "is_active"
        @hash["max_duration"] = "max_duration"
        @hash["name"] = "name"
        @hash["owner_id"] = "owner_id"
        @hash["price_model_id"] = "price_model_id"
        @hash["resources"] = "resources"
        @hash["schedules"] = "schedules"
        @hash["short_name"] = "short_name"
      end
      @hash
    end

    def initialize(categories = nil,
                   description = nil,
                   duration = nil,
                   id = nil,
                   is_active = nil,
                   max_duration = nil,
                   name = nil,
                   owner_id = nil,
                   price_model_id = nil,
                   resources = nil,
                   schedules = nil,
                   short_name = nil)
      @categories = categories
      @description = description
      @duration = duration
      @id = id
      @is_active = is_active
      @max_duration = max_duration
      @name = name
      @owner_id = owner_id
      @price_model_id = price_model_id
      @resources = resources
      @schedules = schedules
      @short_name = short_name
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        categories = hash['categories']
        description = hash['description']
        duration = hash['duration']
        id = hash['id']
        is_active = hash['is_active']
        max_duration = hash['max_duration']
        name = hash['name']
        owner_id = hash['owner_id']
        price_model_id = hash['price_model_id']
        resources = hash['resources']
        schedules = hash['schedules']
        short_name = hash['short_name']

        # Create object from extracted values
        EntitiesServiceResponse.new(categories,
                                    description,
                                    duration,
                                    id,
                                    is_active,
                                    max_duration,
                                    name,
                                    owner_id,
                                    price_model_id,
                                    resources,
                                    schedules,
                                    short_name)
      end
    end
  end
end
