# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class GenderEnum
    # TODO: Write general description for F
    # TODO: Write general description for M
    # TODO: Write general description for ENUM_TG
    GENDER_ENUM = [F = 'F', M = 'M', ENUM_TG = 'T/G']
  end
end