# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class OccurrenceEnum
    # TODO: Write general description for ENUM_4TH_TO_LAST
    # TODO: Write general description for ENUM_3RD_TO_LAST
    # TODO: Write general description for ENUM_2ND_TO_LAST
    # TODO: Write general description for LAST
    # TODO: Write general description for EVERY
    # TODO: Write general description for FIRST
    # TODO: Write general description for ENUM_2ND
    # TODO: Write general description for ENUM_3RD
    # TODO: Write general description for ENUM_4TH
    # TODO: Write general description for ENUM_5TH
    # TODO: Write general description for ENUM_6TH
    # TODO: Write general description for ENUM_7TH
    # TODO: Write general description for ENUM_8TH
    # TODO: Write general description for ENUM_9TH
    # TODO: Write general description for ENUM_10TH
    OCCURRENCE_ENUM = [ENUM_4TH_TO_LAST = '4th_to_last', ENUM_3RD_TO_LAST = '3rd_to_last', ENUM_2ND_TO_LAST = '2nd_to_last', LAST = 'last', EVERY = 'every', FIRST = 'first', ENUM_2ND = '2nd', ENUM_3RD = '3rd', ENUM_4TH = '4th', ENUM_5TH = '5th', ENUM_6TH = '6th', ENUM_7TH = '7th', ENUM_8TH = '8th', ENUM_9TH = '9th', ENUM_10TH = '10th']
  end
end