# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class RecursByEnum
    # TODO: Write general description for ONCE
    # TODO: Write general description for DAILY
    # TODO: Write general description for WEEKEND
    # TODO: Write general description for MON_WED_FRI
    # TODO: Write general description for TUE_THU
    # TODO: Write general description for WEEKDAY
    # TODO: Write general description for WEEKLY
    # TODO: Write general description for MONTHLY
    # TODO: Write general description for YEARLY
    RECURS_BY_ENUM = [ONCE = 'once', DAILY = 'daily', WEEKEND = 'weekend', MON_WED_FRI = 'mon_wed_fri', TUE_THU = 'tue_thu', WEEKDAY = 'weekday', WEEKLY = 'weekly', MONTHLY = 'monthly', YEARLY = 'yearly']
  end
end