# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class SearchQueryResponse < BaseModel
    # TODO: Write general description for this method
    # @return [EntitiesSearchResponse]
    attr_accessor :results

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["results"] = "results"
      end
      @_hash
    end

    def initialize(results = nil)
      @results = results
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      results = EntitiesSearchResponse.from_hash(hash['results']) if hash['results']

      # Create object from extracted values
      SearchQueryResponse.new(results)
    end
  end
end
