# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class UpdateUserByIdBody < BaseModel
    # User's email address
    # @return [String]
    attr_accessor :email

    # Optional first name
    # @return [String]
    attr_accessor :first_name

    # Optional last name
    # @return [String]
    attr_accessor :last_name

    # Optional name for your Business/Organization
    # @return [String]
    attr_accessor :business_name

    # Optional website URL
    # @return [String]
    attr_accessor :external_url

    # Optional vanity url - ex: www.gonebusy.com/[permalink] - must be unique
    # @return [String]
    attr_accessor :permalink

    # Optional timezone
    # @return [String]
    attr_accessor :timezone

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["email"] = "email"
        @_hash["first_name"] = "first_name"
        @_hash["last_name"] = "last_name"
        @_hash["business_name"] = "business_name"
        @_hash["external_url"] = "external_url"
        @_hash["permalink"] = "permalink"
        @_hash["timezone"] = "timezone"
      end
      @_hash
    end

    def initialize(email = nil,
                   first_name = nil,
                   last_name = nil,
                   business_name = nil,
                   external_url = nil,
                   permalink = nil,
                   timezone = nil)
      @email = email
      @first_name = first_name
      @last_name = last_name
      @business_name = business_name
      @external_url = external_url
      @permalink = permalink
      @timezone = timezone
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      email = hash['email']
      first_name = hash['first_name']
      last_name = hash['last_name']
      business_name = hash['business_name']
      external_url = hash['external_url']
      permalink = hash['permalink']
      timezone = hash['timezone']

      # Create object from extracted values
      UpdateUserByIdBody.new(email,
                             first_name,
                             last_name,
                             business_name,
                             external_url,
                             permalink,
                             timezone)
    end
  end
end
