# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class UpdatePricingModelByIdResponse < BaseModel
    # TODO: Write general description for this method
    # @return [EntitiesPricingModelResponse]
    attr_accessor :pricing_model

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["pricing_model"] = "pricing_model"
      end
      @_hash
    end

    def initialize(pricing_model = nil)
      @pricing_model = pricing_model
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      pricing_model = EntitiesPricingModelResponse.from_hash(hash['pricing_model']) if hash['pricing_model']

      # Create object from extracted values
      UpdatePricingModelByIdResponse.new(pricing_model)
    end
  end
end
