# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module Gonebusy
  class UpdatePricingModelByIdBody < BaseModel
    # PricingModel Name
    # @return [String]
    attr_accessor :name

    # Optional Notes Field
    # @return [String]
    attr_accessor :notes

    # Price
    # @return [Float]
    attr_accessor :price

    # 3 Letter ISO Currency Code
    # @return [String]
    attr_accessor :currency

    # A mapping from model property names to API property names
    def self.names
      if @_hash.nil?
        @_hash = {}
        @_hash["name"] = "name"
        @_hash["notes"] = "notes"
        @_hash["price"] = "price"
        @_hash["currency"] = "currency"
      end
      @_hash
    end

    def initialize(name = nil,
                   notes = nil,
                   price = nil,
                   currency = nil)
      @name = name
      @notes = notes
      @price = price
      @currency = currency
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash
      name = hash['name']
      notes = hash['notes']
      price = hash['price']
      currency = hash['currency']

      # Create object from extracted values
      UpdatePricingModelByIdBody.new(name,
                                     notes,
                                     price,
                                     currency)
    end
  end
end
